services:
  web:
    build: .  # Строим образ для сервиса web из текущей директории
    command: python manage.py runserver 0.0.0.0:8000  # Команда для запуска сервера Django
    volumes:
      - .:/app  # Монтируем текущую директорию на /app внутри контейнера
    ports:
      - "8000:8000"  # Пробрасываем порт 8000 на хосте к порту 8000 в контейнере
    depends_on:
      - db  # Сервис web зависит от сервиса db

  db:
    image: postgres  # Используем образ postgres для сервиса db
    environment:
      POSTGRES_DB: todo  # Устанавливаем переменную окружения для имени базы данных
      POSTGRES_USER: user  # Устанавливаем переменную окружения для имени пользователя
      POSTGRES_PASSWORD: password  # Устанавливаем переменную окружения для пароля

  nginx:
    image: nginx:alpine  # Используем образ nginx:alpine для сервиса nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Монтируем файл конфигурации nginx из текущей директории в контейнер
    ports:
      - "80:80"  # Пробрасываем порт 80 на хосте к порту 80 в контейнере
    depends_on:
      - web  # Сервис nginx зависит от сервиса web
